package entity;
// Generated Feb 14, 2017 6:22:11 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Hours generated by hbm2java
 */
@Entity
@Table(name="hours"
    ,catalog="projekat"
)
public class Hours  implements java.io.Serializable {


     private Integer idhours;
     private Event event;
     private String performer;
     private Date startTime;
     private Date endTime;
     private boolean cancelled;
     
     @Column(name="Cancelled", nullable=false)
    public boolean getCancelled() {
        return cancelled;
    }

    public void setCancelled(boolean cancelled) {
        this.cancelled = cancelled;
    }
     
    public Hours() {
    }

    public Hours(Event event, String performer, Date startTime, Date endTime) {
       this.event = event;
       this.performer = performer;
       this.startTime = startTime;
       this.endTime = endTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDhours", unique=true, nullable=false)
    public Integer getIdhours() {
        return this.idhours;
    }
    
    public void setIdhours(Integer idhours) {
        this.idhours = idhours;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="IDEvent", nullable=false)
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }

    
    @Column(name="Performer", nullable=false, length=50)
    public String getPerformer() {
        return this.performer;
    }
    
    public void setPerformer(String performer) {
        this.performer = performer;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="StartTime", nullable=false, length=19)
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EndTime", nullable=false, length=19)
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
    
    



}


