package entity;
// Generated Feb 14, 2017 6:22:11 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Link generated by hbm2java
 */
@Entity
@Table(name="link"
    ,catalog="projekat"
)
public class Link  implements java.io.Serializable {


     private Integer idlink;
     private Event event;
     private String link;
     private String name;

    public Link() {
    }

    public Link(Event event, String link, String name) {
       this.event = event;
       this.link = link;
       this.name = name;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDLink", unique=true, nullable=false)
    public Integer getIdlink() {
        return this.idlink;
    }
    
    public void setIdlink(Integer idlink) {
        this.idlink = idlink;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="IDEvent", nullable=false)
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }

    
    @Column(name="Link", nullable=false, length=65535)
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }

    
    @Column(name="Name", nullable=false, length=30)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


